{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fortresswaf.fullname" . }}-dashboard
  labels:
    {{- include "fortresswaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
    {{- with .Values.ingress.extraTls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "fortresswaf.fullname" . }}-dashboard
                port:
                  number: {{ .Values.service.dashboard.ports.http }}
    {{- with .Values.ingress.extraRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
