{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fortresswaf.fullname" . }}-data
  labels:
    {{- include "fortresswaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.sizes.fortress }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fortresswaf.fullname" . }}-ml
  labels:
    {{- include "fortresswaf.labels" . | nindent 4 }}
    app.kubernetes.io/component: ml-engine
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.sizes.ml }}
{{- end }}
