apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fortresswaf.secretName" . }}
  labels:
    {{- include "fortresswaf.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.existingSecretName }}
  {{ else }}
  db-password: {{ .Values.secrets.dbPassword | default (randAlphaNum 32) | b64enc | quote }}
  redis-password: {{ .Values.secrets.redisPassword | default (randAlphaNum 32) | b64enc | quote }}
  opensearch-password: {{ .Values.secrets.opensearchPassword | default (randAlphaNum 32) | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | default (randAlphaNum 64) | b64enc | quote }}
  {{- if .Values.secrets.tls.cert }}
  tls.crt: {{ .Values.secrets.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.secrets.tls.key | b64enc | quote }}
  {{- end }}
  {{- end }}
