{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fortresswaf.serviceAccountName" . }}
  labels:
    {{- include "fortresswaf.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- if and .Values.rbac.create .Values.rbac.clusterRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fortresswaf.fullname" . }}-cluster
  labels:
    {{- include "fortresswaf.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.clusterRules | nindent 2 }}
  {{- with .Values.rbac.extraRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- if .Values.rbac.clusterRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fortresswaf.fullname" . }}-cluster
  labels:
    {{- include "fortresswaf.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fortresswaf.fullname" . }}-cluster
subjects:
  - kind: ServiceAccount
    name: {{ include "fortresswaf.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
